from typing import Any

class Field:
    def __init__(self, **kwargs: Any) -> None: ...

class Instance(Field):
    def __init__(self, ty: type, **kwargs: Any) -> None: ...

class Str(Instance):
    def __init__(self, **kwargs: Any) -> None: ...

class Int(Instance):
    def __init__(self, **kwargs: Any) -> None: ...

class Bool(Instance):
    def __init__(self, **kwargs: Any) -> None: ...

class Float(Instance):
    def __init__(self, **kwargs: Any) -> None: ...

class Bytes(Instance):
    def __init__(self, **kwargs: Any) -> None: ...

class DateTime(Instance):
    def __init__(self, format: str = ..., **kwargs: Any) -> None: ...

class Date(DateTime):
    def __init__(self, format: str = ..., **kwargs: Any) -> None: ...

class Time(DateTime):
    def __init__(self, format: str = ..., **kwargs: Any) -> None: ...

class Nested(Instance):
    def __init__(self, model_cls: type, **kwargs: Any) -> None: ...

class Optional(Field):
    def __init__(self, inner: Any = ..., **kwargs: Any) -> None: ...

class List(Field):
    def __init__(self, element: Any = ..., **kwargs: Any) -> None: ...

class Set(Field):
    def __init__(self, element: Any = ..., **kwargs: Any) -> None: ...

class Tuple(Field):
    def __init__(self, *elements: Any, **kwargs: Any) -> None: ...

class Dict(Field):
    def __init__(
        self,
        key: Any = ...,
        value: Any = ...,
        **kwargs: Any,
    ) -> None: ...

class Flatten(Nested): ...

class Literal(Field):
    def __init__(self, value: Any, **kwargs: Any) -> None: ...

class Choice(Field):
    def __init__(self, choices: Any, **kwargs: Any) -> None: ...
