from collections import OrderedDict
from typing import Any, Self

class Model:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def to_dict(self) -> OrderedDict[str, Any]: ...
    def to_json(self, **kwargs: Any) -> str: ...
    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Self: ...
    @classmethod
    def from_json(cls, s: str, **kwargs: Any) -> Self: ...
